import { PostMeta } from "../types";

const posts: PostMeta[] = [
  {
    title: "Jonathan (JEEMZ) BGMI Settings, Sensitivity & Controls (2026)",
    slug: "jonathan-bgmi-settings",
    description:
      "Copy Jonathan's exact BGMI settings including sensitivity, controls layout, gyroscope, and device info.",
    category: "pro-settings",
    subcategory: "bgmi",
    tags: ["bgmi", "jonathan", "pro-settings"],
    date: "2026-03-10",
    author: "RaidGG Team",
    player: "Jonathan",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&h=450&fit=crop",
    imageAlt: "Gaming mouse similar to Jonathan BGMI pro setup",
    sections: [
      {
        type: "paragraph",
        html: "<strong>Jonathan</strong> is widely regarded as one of the most talented <strong>BGMI</strong> players in India, competing for <strong>GodLike Esports</strong>. Known for his hyper-aggressive playstyle and ability to win fights most players would avoid, he is a fan favorite and feared opponent. His settings are optimized for fast target acquisition and close-range dominance using a <strong>4-finger claw grip</strong>.",
      },
      {
        type: "heading",
        level: 2,
        text: "Jonathan BGMI Sensitivity Settings",
      },
      {
        type: "specs",
        label: "Sensitivity Settings",
        rows: [
          ["Camera (TPP No Scope)", "150%"],
          ["Camera (FPP No Scope)", "120%"],
          ["Red Dot / Holographic", "100%"],
          ["2x Scope", "80%"],
          ["3x Scope", "60%"],
          ["4x Scope", "45%"],
          ["6x Scope", "30%"],
          ["8x Scope", "20%"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Gyroscope Settings",
      },
      {
        type: "specs",
        label: "Gyroscope Sensitivity",
        rows: [
          ["Gyroscope Mode", "Always On"],
          ["Gyroscope (TPP No Scope)", "300%"],
          ["Gyroscope (FPP No Scope)", "250%"],
          ["Red Dot / Holographic", "200%"],
          ["3x Scope", "120%"],
          ["4x Scope", "80%"],
          ["6x Scope", "50%"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Graphics Settings",
      },
      {
        type: "specs",
        label: "Video & Graphics",
        rows: [
          ["Graphics Quality", "Smooth"],
          ["Frame Rate", "Extreme (90 FPS)"],
          ["Brightness", "60%"],
          ["Color Mode", "Default"],
          ["Anti-Aliasing", "Off"],
          ["Shadows", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Gear & Device Setup",
      },
      {
        type: "specs",
        label: "Device Info",
        rows: [
          ["Primary Device", "iPhone 15 Pro Max"],
          ["Display", "6.7-inch OLED, 120Hz"],
          ["Processor", "Apple A17 Pro"],
          ["Accessories", "Phone cooler, finger sleeves"],
          ["Controls Layout", "4-Finger Claw"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "How to Use Jonathan's Settings",
      },
      {
        type: "list",
        style: "bullet",
        items: [
          "Start at <strong>80% of Jonathan's sensitivity values</strong> and increase gradually as your muscle memory develops.",
          "Place fire buttons at the <strong>top corners</strong> of the screen for index finger access — this is the core of claw grip.",
          "Enable <strong>Always On gyroscope</strong> only after you are comfortable with touch sensitivity alone.",
          "Use a <strong>phone cooler</strong> to prevent thermal throttling during long sessions.",
          "Wear <strong>finger sleeves</strong> for consistent swipe response regardless of sweat.",
          "Practice claw grip in casual matches before switching to ranked — it takes 2–3 weeks to feel natural.",
        ],
      },
      {
        type: "callout",
        variant: "warning",
        html: "<strong>Don't copy settings blindly.</strong> Jonathan's values are tuned for his specific device and thousands of hours of muscle memory. Use them as a starting point, adjust for your screen size and grip comfort, and commit to the new settings for at least two weeks before judging.",
      },
      {
        type: "internal-links",
        title: "Related BGMI Guides",
        links: [
          { text: "Neyoo BGMI Settings & Sensitivity", href: "/pro-settings/bgmi/neyoo-bgmi-settings/" },
          { text: "BGMI Redeem Codes (Today)", href: "/redeem-codes/bgmi/bgmi-redeem-codes-today/" },
          { text: "Best BGMI Sensitivity for Gyroscope", href: "/guides/bgmi/best-bgmi-sensitivity-gyroscope/" },
        ],
      },
    ],
  },
  {
    title: "TenZ Valorant Settings, Crosshair & Keybinds (2026)",
    slug: "tenz-valorant-settings",
    description:
      "TenZ's complete Valorant setup: crosshair code, mouse settings, keybinds, and PC specs.",
    category: "pro-settings",
    subcategory: "valorant",
    tags: ["valorant", "tenz", "pro-settings"],
    date: "2026-03-09",
    author: "RaidGG Team",
    featured: true,
    player: "TenZ",
    readTime: "6 min",
    image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&h=450&fit=crop",
    imageAlt: "Gaming monitor matching TenZ Valorant display settings",
    sections: [
      {
        type: "paragraph",
        html: "<strong>TenZ</strong> is one of the most recognized names in professional <strong>Valorant</strong>, competing for <strong>Sentinels</strong> since 2021. Known for his flashy aim and creative playstyle, he has inspired millions of players worldwide. His settings philosophy is rooted in years of competitive FPS experience going back to his <strong>CS:GO days</strong>, emphasizing precision over raw speed.",
      },
      {
        type: "heading",
        level: 2,
        text: "TenZ Mouse Settings",
      },
      {
        type: "specs",
        label: "Mouse & Sensitivity",
        rows: [
          ["DPI", "800"],
          ["In-Game Sensitivity", "0.22"],
          ["eDPI", "176"],
          ["Polling Rate", "1000 Hz"],
          ["Raw Input", "On"],
          ["Windows Sensitivity", "6/11"],
          ["Mouse Acceleration", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Crosshair Settings",
      },
      {
        type: "specs",
        label: "Crosshair",
        rows: [
          ["Color", "Cyan"],
          ["Crosshair Code", "0;P;c;5;h;0;m;1;0l;4;0o;2;0a;1;0f;0;1b;0"],
          ["Inner Lines", "On"],
          ["Outer Lines", "Off"],
          ["Center Dot", "Off"],
          ["Movement Error", "Off"],
          ["Firing Error", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Video & Graphics Settings",
      },
      {
        type: "specs",
        label: "Video Settings",
        rows: [
          ["Resolution", "1920x1080"],
          ["Display Mode", "Fullscreen"],
          ["Frame Rate Limit", "Unlocked"],
          ["Material Quality", "Low"],
          ["Texture Quality", "Low"],
          ["Detail Quality", "Low"],
          ["Vignette", "Off"],
          ["Anti-Aliasing", "MSAA 4x"],
          ["Anisotropic Filtering", "4x"],
          ["Bloom", "Off"],
          ["Distortion", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Gear & Setup",
      },
      {
        type: "specs",
        label: "TenZ's Peripherals",
        rows: [
          ["Mouse", "Finalmouse UltralightX"],
          ["Mousepad", "Artisan FX Zero (XL)"],
          ["Keyboard", "Custom 65% mechanical"],
          ["Monitor", "ASUS ROG Swift 360Hz"],
          ["Headset", "HyperX Cloud Alpha"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "How to Use TenZ's Settings",
      },
      {
        type: "list",
        style: "bullet",
        items: [
          "Use a <strong>large mousepad (45cm+ wide)</strong> — TenZ's low eDPI requires long arm swipes for 180-degree turns.",
          "Keep <strong>Raw Input On</strong> and Windows sensitivity at 6/11 so DPI values translate accurately.",
          "Practice <strong>crosshair placement</strong> religiously — low sens rewards head-level pre-aiming at all times.",
          "Run a <strong>240Hz or higher monitor</strong>; the smoothness difference is significant at his low sensitivity.",
          "Disable <strong>Mouse Acceleration</strong> in both Windows and the game for consistent muscle memory.",
          "Start Deathmatch sessions at the beginning of every play session to warm up your arm before ranked.",
        ],
      },
      {
        type: "callout",
        variant: "tip",
        html: "<strong>Low sensitivity takes time.</strong> TenZ's eDPI of 176 is one of the lowest in professional Valorant. If you're coming from a higher sensitivity, expect 3–4 weeks of adjustment. Don't give up early — the precision gains are worth it.",
      },
      {
        type: "internal-links",
        title: "Related Valorant Guides",
        links: [
          { text: "Demon1 Valorant Settings & Crosshair", href: "/pro-settings/valorant/demon1-valorant-settings/" },
          { text: "Aspas Valorant Settings & Keybinds", href: "/pro-settings/valorant/aspas-valorant-settings/" },
          { text: "Best Valorant Crosshair Codes", href: "/guides/valorant/best-valorant-crosshair-codes/" },
        ],
      },
    ],
  },
  {
    title: "Ajjubhai Free Fire Settings & Sensitivity (2026)",
    slug: "ajjubhai-free-fire-settings",
    description:
      "Total Gaming Ajjubhai's Free Fire sensitivity, HUD layout, and device setup for 2026.",
    category: "pro-settings",
    subcategory: "free-fire",
    tags: ["free-fire", "ajjubhai", "pro-settings"],
    date: "2026-03-08",
    author: "RaidGG Team",
    player: "Ajjubhai",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&h=450&fit=crop",
    imageAlt: "Mechanical keyboard layout for Ajjubhai Free Fire settings",
    sections: [
      {
        type: "paragraph",
        html: "<strong>Ajjubhai</strong>, the creator behind <strong>Total Gaming</strong>, is the biggest <strong>Free Fire</strong> content creator in the world with over <strong>40 million YouTube subscribers</strong>. While primarily a content creator, his gameplay skills are impressive and his settings are optimized for entertaining yet effective play. Millions of Free Fire players use his sensitivity and HUD layout as their starting point.",
      },
      {
        type: "heading",
        level: 2,
        text: "Ajjubhai Free Fire Sensitivity Settings",
      },
      {
        type: "specs",
        label: "Sensitivity",
        rows: [
          ["General Sensitivity", "100"],
          ["Red Dot Sensitivity", "90"],
          ["2x Scope Sensitivity", "80"],
          ["4x Scope Sensitivity", "65"],
          ["Sniper Scope Sensitivity", "55"],
          ["Free Look Sensitivity", "80"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "HUD & Controls Layout",
      },
      {
        type: "specs",
        label: "Controls",
        rows: [
          ["Control Style", "2-Thumb"],
          ["Fire Button", "Right side, large"],
          ["Aim Button", "Left side"],
          ["Crouch", "Auto-crouch enabled"],
          ["Jump", "Left thumb area"],
          ["HUD Size", "Medium"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Graphics Settings",
      },
      {
        type: "specs",
        label: "Video & Graphics",
        rows: [
          ["Graphics Quality", "Ultra"],
          ["Frame Rate", "Ultra (60 FPS)"],
          ["Brightness", "55%"],
          ["Custom HUD Opacity", "80%"],
          ["Anti-Aliasing", "On"],
          ["Color Temperature", "Default"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Gear & Device Setup",
      },
      {
        type: "specs",
        label: "Device Info",
        rows: [
          ["Primary Device", "Samsung Galaxy S24 Ultra"],
          ["Display", "6.8-inch QHD+, 120Hz"],
          ["RAM", "12 GB"],
          ["Processor", "Snapdragon 8 Gen 3"],
          ["Accessories", "Gaming trigger buttons"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "How to Use Ajjubhai's Settings",
      },
      {
        type: "list",
        style: "bullet",
        items: [
          "His settings work best on phones with <strong>screens between 6.5–6.8 inches</strong> — the HUD layout is tuned for that size.",
          "Tablet players should <strong>increase sensitivity by 10–15%</strong> to account for larger swipe distances.",
          "Keep graphics on <strong>Ultra with 60 FPS</strong> if your device supports it for the smoothest gameplay.",
          "Use the <strong>2-thumb layout</strong> as shown — it is accessible and does not require claw grip skills.",
          "Players on older devices should <strong>drop to High graphics</strong> to avoid frame drops during intense fights.",
          "Enable <strong>Auto-crouch</strong> to free up a button slot for more responsive controls.",
        ],
      },
      {
        type: "callout",
        variant: "info",
        html: "Ajjubhai's settings are designed for <strong>content creation and casual ranked play</strong>. If you're aiming for tournament-level competition, consider a claw grip layout and higher sensitivity for faster reactions.",
      },
      {
        type: "internal-links",
        title: "Related Free Fire Guides",
        links: [
          { text: "Free Fire Redeem Codes (Today)", href: "/redeem-codes/free-fire/free-fire-redeem-codes-today/" },
          { text: "Best Free Fire Sensitivity Settings", href: "/guides/free-fire/best-free-fire-sensitivity/" },
          { text: "Free Fire Diamond Top-Up Guide", href: "/guides/free-fire/free-fire-diamond-top-up/" },
        ],
      },
    ],
  },
  {
    title: "Bugha Fortnite Settings & Keybinds (2026)",
    slug: "bugha-fortnite-settings",
    description:
      "Bugha's Fortnite settings: keybinds, mouse sensitivity, video settings, and complete setup.",
    category: "pro-settings",
    subcategory: "fortnite",
    tags: ["fortnite", "bugha", "pro-settings"],
    date: "2026-03-07",
    author: "RaidGG Team",
    player: "Bugha",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&h=450&fit=crop",
    imageAlt: "Pro gaming mouse used in Bugha Fortnite setup",
    sections: [
      {
        type: "paragraph",
        html: "<strong>Bugha</strong> cemented his legacy by winning the <strong>Fortnite World Cup in 2019</strong>, becoming the most famous competitive Fortnite player of all time. He has remained one of the most consistent players in the game ever since, with mechanical skill in building and editing that is considered among the best in the world. His settings are refined over thousands of hours of competitive play for <strong>maximum building speed and edit efficiency</strong>.",
      },
      {
        type: "heading",
        level: 2,
        text: "Bugha Mouse Settings",
      },
      {
        type: "specs",
        label: "Mouse & Sensitivity",
        rows: [
          ["DPI", "400"],
          ["X-Axis Sensitivity", "12.0%"],
          ["Y-Axis Sensitivity", "12.0%"],
          ["Targeting Sensitivity", "28%"],
          ["Scope Sensitivity", "37%"],
          ["Polling Rate", "1000 Hz"],
          ["Mouse Acceleration", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Keybinds",
      },
      {
        type: "specs",
        label: "Building & Edit Keybinds",
        rows: [
          ["Wall", "Mouse Button 4"],
          ["Floor", "C"],
          ["Ramp", "Mouse Button 5"],
          ["Roof / Cone", "F"],
          ["Edit", "E (Edit on Release: On)"],
          ["Crouch", "Left Ctrl"],
          ["Sprint", "Always Sprint: On"],
          ["Building Edit Reset", "On"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Video & Graphics Settings",
      },
      {
        type: "specs",
        label: "Video Settings",
        rows: [
          ["Resolution", "1920x1080"],
          ["Display Mode", "Fullscreen"],
          ["Frame Rate Limit", "Unlimited"],
          ["3D Resolution", "100%"],
          ["View Distance", "Epic"],
          ["Shadows", "Off"],
          ["Anti-Aliasing & Super Resolution", "Epic"],
          ["Textures", "Low"],
          ["Effects", "Low"],
          ["Post Processing", "Low"],
          ["Vsync", "Off"],
          ["Motion Blur", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Gear & Setup",
      },
      {
        type: "specs",
        label: "Bugha's Peripherals",
        rows: [
          ["Mouse", "Logitech G502 X Plus"],
          ["Mousepad", "Corsair MM300 Pro Extended"],
          ["Keyboard", "HyperX Alloy Origins 60"],
          ["Monitor", "BenQ ZOWIE XL2546K (240Hz)"],
          ["Headset", "HyperX Cloud II Wireless"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "How to Use Bugha's Settings",
      },
      {
        type: "list",
        style: "bullet",
        items: [
          "Bind Wall to a <strong>mouse side button</strong> — this is the most important single change for building speed.",
          "Enable <strong>Edit on Release</strong> in Fortnite settings; it confirms your edit the moment you release the key.",
          "Practice build sequences in <strong>Creative mode for at least 60 minutes daily</strong> before taking new binds to ranked.",
          "Keep <strong>Shadows Off</strong> and Effects/Textures Low to maximize frame rate during intense build fights.",
          "Use <strong>Always Sprint</strong> so you never accidentally walk during a rotation.",
          "Set View Distance to <strong>Epic</strong> — unlike other settings, this one actually affects gameplay visibility.",
        ],
      },
      {
        type: "callout",
        variant: "warning",
        html: "<strong>Keybinds require weeks of practice.</strong> Bugha's building binds assume high finger dexterity built over years. Do not jump into competitive matches immediately — spend at least 2 weeks in Creative before using them in ranked.",
      },
      {
        type: "internal-links",
        title: "Related Fortnite Guides",
        links: [
          { text: "Best Fortnite Keybinds for PC", href: "/guides/fortnite/best-fortnite-keybinds-pc/" },
          { text: "Best Fortnite Settings for Performance", href: "/guides/fortnite/best-fortnite-settings-performance/" },
          { text: "Fortnite Creative Edit Course Codes", href: "/guides/fortnite/fortnite-edit-course-codes/" },
        ],
      },
    ],
  },
  {
    title: "ImperialHal Apex Legends Settings & Setup (2026)",
    slug: "imperialhal-apex-settings",
    description:
      "ImperialHal's complete Apex Legends settings, sensitivity, keybinds, and streaming gear.",
    category: "pro-settings",
    subcategory: "apex-legends",
    tags: ["apex-legends", "imperialhal", "pro-settings"],
    date: "2026-03-06",
    author: "RaidGG Team",
    player: "ImperialHal",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&h=450&fit=crop",
    imageAlt: "Gaming monitor with ImperialHal Apex Legends settings",
    sections: [
      {
        type: "paragraph",
        html: "<strong>ImperialHal</strong> (Philip Dosen) is the long-time captain and <strong>IGL of TSM</strong>, widely considered the greatest competitive <strong>Apex Legends</strong> player of all time. His resume includes multiple <strong>ALGS Championships</strong> and a reputation for making clutch plays under extreme pressure. What sets ImperialHal apart is not raw mechanics but his extraordinary <strong>game sense, decision-making, and leadership</strong>.",
      },
      {
        type: "heading",
        level: 2,
        text: "ImperialHal Controller Settings",
      },
      {
        type: "specs",
        label: "Controller & Sensitivity",
        rows: [
          ["Input Device", "PlayStation DualSense / Xbox Controller"],
          ["Look Sensitivity", "4"],
          ["ADS Sensitivity", "4"],
          ["Response Curve", "Classic"],
          ["Deadzone (Left)", "1"],
          ["Deadzone (Right)", "1"],
          ["Crouch Hold", "Hold"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Video & Graphics Settings",
      },
      {
        type: "specs",
        label: "Video Settings",
        rows: [
          ["Resolution", "1920x1080"],
          ["Display Mode", "Fullscreen"],
          ["V-Sync", "Disabled"],
          ["Anti-Aliasing", "None"],
          ["Texture Streaming Budget", "Low (2GB VRAM)"],
          ["Texture Filtering", "Bilinear"],
          ["Ambient Occlusion Quality", "Disabled"],
          ["Sun Shadow Coverage", "Low"],
          ["Spot Shadow Detail", "Disabled"],
          ["Model Detail", "Low"],
          ["Effects Detail", "Low"],
          ["FPS Cap", "Uncapped"],
          ["Field of View", "110"],
          ["FOV Ability Scaling", "Disabled"],
          ["Color Blind Mode", "Tritanopia (for better vis)"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Gear & Setup",
      },
      {
        type: "specs",
        label: "ImperialHal's Peripherals",
        rows: [
          ["Controller", "DualSense Edge"],
          ["Monitor", "BenQ ZOWIE XL2546K (240Hz)"],
          ["Headset", "HyperX Cloud Alpha Pro"],
          ["PC CPU", "Intel Core i9-14900K"],
          ["PC GPU", "NVIDIA RTX 4090"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "How to Use ImperialHal's Settings",
      },
      {
        type: "list",
        style: "bullet",
        items: [
          "Set <strong>Response Curve to Classic</strong> for a linear feel that rewards consistent thumb control.",
          "Keep <strong>both deadzones at 1</strong> for maximum stick responsiveness without drift.",
          "Enable <strong>Tritanopia color-blind mode</strong> even if you're not color-blind — it makes enemy outlines easier to spot.",
          "Set <strong>FOV to 110</strong> for maximum situational awareness during third-party scenarios.",
          "Run <strong>all graphics on Low</strong> — ImperialHal prioritizes frame rate and visual clarity over visuals.",
          "Focus on <strong>ring reading and rotation timing</strong> — ImperialHal's biggest skill advantage is not his settings.",
        ],
      },
      {
        type: "callout",
        variant: "info",
        html: "ImperialHal's greatest lesson: <strong>settings are only 5% of your performance</strong>. His real advantage is game sense built over thousands of competitive matches. Use his settings as a baseline and invest your energy into understanding positioning and zone strategy.",
      },
      {
        type: "internal-links",
        title: "Related Apex Legends Guides",
        links: [
          { text: "Best Apex Legends Settings for PC", href: "/guides/apex-legends/best-apex-legends-settings-pc/" },
          { text: "Best Apex Legends Characters Tier List", href: "/guides/apex-legends/apex-legends-tier-list/" },
          { text: "Apex Legends Ranked Tips", href: "/guides/apex-legends/apex-legends-ranked-tips/" },
        ],
      },
    ],
  },
  {
    title: "Demon1 Valorant Settings, Crosshair & Sensitivity (2026)",
    slug: "demon1-valorant-settings",
    description:
      "Demon1's complete Valorant setup for 2026: crosshair code, mouse DPI, eDPI, keybinds, video settings, and PC specs.",
    category: "pro-settings",
    subcategory: "valorant",
    tags: ["valorant", "demon1", "pro-settings", "sentinels"],
    date: "2026-03-11",
    author: "RaidGG Team",
    player: "Demon1",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&h=450&fit=crop",
    imageAlt: "High-performance gaming mouse for Demon1 Valorant setup",
    sections: [
      {
        type: "paragraph",
        html: "<strong>Demon1</strong> burst onto the <strong>Valorant</strong> scene with an aggressive duelist playstyle that redefined entry fragging at the highest level. Playing for <strong>Sentinels</strong>, he quickly became one of the most mechanically gifted players in the world, winning multiple <strong>VCT MVP awards</strong>. With an <strong>eDPI of 216</strong>, his settings are tuned for the fast-paced, peek-heavy style that makes him so dangerous.",
      },
      {
        type: "heading",
        level: 2,
        text: "Demon1 Mouse Settings",
      },
      {
        type: "specs",
        label: "Mouse & Sensitivity",
        rows: [
          ["DPI", "800"],
          ["In-Game Sensitivity", "0.27"],
          ["eDPI", "216"],
          ["Polling Rate", "1000 Hz"],
          ["Raw Input Buffer", "On"],
          ["Windows Sensitivity", "6/11"],
          ["Mouse Acceleration", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Crosshair Settings",
      },
      {
        type: "specs",
        label: "Crosshair",
        rows: [
          ["Color", "Cyan"],
          ["Crosshair Code", "0;P;c;5;h;0;m;1;0l;4;0o;2;0a;1;0f;0;1b;0"],
          ["Inner Lines Opacity", "1"],
          ["Inner Lines Length", "4"],
          ["Inner Lines Thickness", "2"],
          ["Inner Lines Offset", "2"],
          ["Outer Lines", "Off"],
          ["Center Dot", "Off"],
          ["Movement / Firing Error", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Video & Graphics Settings",
      },
      {
        type: "specs",
        label: "Video Settings",
        rows: [
          ["Resolution", "1920x1080"],
          ["Display Mode", "Fullscreen"],
          ["Frame Rate Limit", "Unlocked"],
          ["Material Quality", "Low"],
          ["Texture Quality", "Low"],
          ["Detail Quality", "Low"],
          ["UI Quality", "Low"],
          ["Vignette", "Off"],
          ["Anti-Aliasing", "MSAA 4x"],
          ["Anisotropic Filtering", "4x"],
          ["Bloom", "Off"],
          ["Distortion", "Off"],
          ["First Person Shadows", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Gear & Setup",
      },
      {
        type: "specs",
        label: "Demon1's Peripherals",
        rows: [
          ["Mouse", "Finalmouse UltralightX"],
          ["Mousepad", "Artisan FX Zero (XL)"],
          ["Keyboard", "Wooting 60HE"],
          ["Monitor", "Alienware AW2524H (360Hz)"],
          ["Headset", "EPOS H6PRO"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "How to Use Demon1's Settings",
      },
      {
        type: "list",
        style: "bullet",
        items: [
          "Practice <strong>counter-strafing</strong> daily in Deathmatch — Demon1's eDPI 216 demands precise stopping before each shot.",
          "Pre-aim <strong>common head-level positions</strong> on every angle before swinging — never peek blind.",
          "Use a <strong>large mousepad (XL size)</strong> to accommodate wide arm-swing movements at this sensitivity.",
          "Keep all video settings on <strong>Low</strong> to remove visual distractions and maximize FPS.",
          "Enable <strong>Raw Input Buffer</strong> in Valorant for the lowest possible input latency.",
          "Study Demon1's <strong>VODs for angle discipline</strong> — his aim duels are won by crosshair placement, not reaction time alone.",
        ],
      },
      {
        type: "callout",
        variant: "tip",
        html: "<strong>Dry peeks win aim duels.</strong> Demon1's low eDPI is specifically designed for the precision required to win 50/50 duels on dry peeks. If you're used to a higher sensitivity, drop it gradually — 10% per week — until you reach his range.",
      },
      {
        type: "internal-links",
        title: "Related Valorant Guides",
        links: [
          { text: "TenZ Valorant Settings & Crosshair", href: "/pro-settings/valorant/tenz-valorant-settings/" },
          { text: "Aspas Valorant Settings & Keybinds", href: "/pro-settings/valorant/aspas-valorant-settings/" },
          { text: "Best Valorant Crosshair Codes", href: "/guides/valorant/best-valorant-crosshair-codes/" },
        ],
      },
    ],
    faqs: [
      { question: "What sensitivity does Demon1 use?", answer: "Demon1 plays on 800 DPI with 0.27 in-game sensitivity for an eDPI of 216. This is slightly lower than average, giving him precise aim for long-range duels." },
      { question: "What crosshair code does Demon1 use?", answer: "Demon1's crosshair code is 0;P;c;5;h;0;m;1;0l;4;0o;2;0a;1;0f;0;1b;0. It's a small cyan crosshair with inner lines only." },
      { question: "What mouse does Demon1 use?", answer: "Demon1 currently uses the Finalmouse UltralightX, paired with a large Artisan FX Zero mousepad for maximum control." },
    ],
  },
  {
    title: "Neyoo BGMI Settings, Sensitivity & Device (2026)",
    slug: "neyoo-bgmi-settings",
    description:
      "Neyoo's exact BGMI settings for 2026: sensitivity, gyroscope, controls layout, graphics settings, and device info.",
    category: "pro-settings",
    subcategory: "bgmi",
    tags: ["bgmi", "neyoo", "pro-settings", "godlike"],
    date: "2026-03-10",
    author: "RaidGG Team",
    player: "Neyoo",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&h=450&fit=crop",
    imageAlt: "Mechanical keyboard used in Neyoo BGMI configuration",
    sections: [
      {
        type: "paragraph",
        html: "<strong>Neyoo</strong> is one of the most decorated <strong>BGMI</strong> esports professionals in India, competing for <strong>GodLike Esports</strong> and winning multiple tournament MVP awards. His consistent performance at both online leagues and LAN events has made him one of the most clutch players in the scene. He is known for his unique dual-device setup — <strong>iPad Pro for tournaments</strong> and smartphone for ranked — combined with <strong>Gyroscope Always On</strong>.",
      },
      {
        type: "heading",
        level: 2,
        text: "Neyoo BGMI Sensitivity Settings",
      },
      {
        type: "specs",
        label: "Camera Sensitivity (Phone)",
        rows: [
          ["TPP No Scope", "130%"],
          ["FPP No Scope", "110%"],
          ["Red Dot / Holographic", "85%"],
          ["2x Scope", "75%"],
          ["3x Scope", "60%"],
          ["4x Scope", "35%"],
          ["6x Scope", "20%"],
          ["8x Scope", "13%"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Gyroscope Settings",
      },
      {
        type: "specs",
        label: "Gyroscope (Always On)",
        rows: [
          ["Gyroscope Mode", "Always On"],
          ["Gyroscope (TPP No Scope)", "280%"],
          ["Gyroscope (FPP No Scope)", "240%"],
          ["Red Dot / Holographic", "200%"],
          ["3x Scope", "120%"],
          ["4x Scope", "80%"],
          ["6x Scope", "50%"],
          ["8x Scope", "30%"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Graphics Settings",
      },
      {
        type: "specs",
        label: "Video & Graphics",
        rows: [
          ["Graphics Quality", "Smooth"],
          ["Frame Rate", "Extreme (90 FPS)"],
          ["Brightness", "50%"],
          ["Color Mode", "Vivid"],
          ["Anti-Aliasing", "Off"],
          ["Shadows", "Off"],
          ["Style", "Colorful"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Gear & Device Setup",
      },
      {
        type: "specs",
        label: "Neyoo's Devices",
        rows: [
          ["Tournament Device", "iPad Pro M4 (12.9-inch)"],
          ["Ranked / Practice Device", "iPhone 16 Pro Max"],
          ["Accessories", "Phone cooler, finger sleeves"],
          ["Controls Layout", "4-Finger Claw"],
          ["Grip Style", "Claw (iPad), Hybrid (Phone)"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "How to Use Neyoo's Settings",
      },
      {
        type: "list",
        style: "bullet",
        items: [
          "Enable <strong>Gyroscope Always On</strong> — this is Neyoo's biggest advantage and requires weeks of dedicated practice to master.",
          "If moving from phone to iPad, <strong>reduce sensitivity by 15–20%</strong> to compensate for the larger screen size.",
          "Run <strong>Smooth graphics + Extreme FPS</strong> — tournament results matter more than visual quality.",
          "Use a <strong>phone cooler</strong> at all times to prevent performance drops from thermal throttling.",
          "Wear <strong>finger sleeves</strong> on your swiping fingers for consistent touch response.",
          "Master the <strong>4-finger claw layout</strong> in casual modes before bringing it to ranked or tournaments.",
        ],
      },
      {
        type: "callout",
        variant: "tip",
        html: "<strong>Gyroscope Always On is an advanced technique.</strong> It takes 4–6 weeks of daily practice to become comfortable. Start with <strong>Gyroscope Scope Only</strong> if you're a beginner, and work your way up gradually.",
      },
      {
        type: "internal-links",
        title: "Related BGMI Guides",
        links: [
          { text: "Jonathan BGMI Settings & Sensitivity", href: "/pro-settings/bgmi/jonathan-bgmi-settings/" },
          { text: "BGMI Redeem Codes (Today)", href: "/redeem-codes/bgmi/bgmi-redeem-codes-today/" },
          { text: "Best BGMI Gyroscope Sensitivity Guide", href: "/guides/bgmi/best-bgmi-gyroscope-sensitivity/" },
        ],
      },
    ],
    faqs: [
      { question: "What device does Neyoo use for BGMI?", answer: "Neyoo plays BGMI on iPad Pro M4 for tournaments and uses an iPhone 16 Pro Max for ranked play. The iPad gives him a larger screen advantage in competitive matches." },
      { question: "Does Neyoo use gyroscope?", answer: "Yes, Neyoo uses gyroscope on 'Always On' mode with customized sensitivity for each scope. Gyroscope helps with recoil control and fast target tracking." },
      { question: "What are Neyoo's camera sensitivity settings?", answer: "Neyoo uses 130% for TPP No Scope, 85% for Red Dot, 60% for 3x, 35% for 4x, and 20% for 6x. These values work best with his gyroscope settings." },
    ],
  },
  {
    title: "Aspas Valorant Settings, Crosshair & Keybinds (2026)",
    slug: "aspas-valorant-settings",
    description:
      "Aspas's complete Valorant configuration: crosshair code, sensitivity, resolution, keybinds, and gear for 2026.",
    category: "pro-settings",
    subcategory: "valorant",
    tags: ["valorant", "aspas", "pro-settings", "loud"],
    date: "2026-03-09",
    author: "RaidGG Team",
    player: "Aspas",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&h=450&fit=crop",
    imageAlt: "Gaming monitor displaying Aspas Valorant settings",
    sections: [
      {
        type: "paragraph",
        html: "<strong>Aspas</strong> is the Brazilian superstar who put <strong>LOUD</strong> on the map as one of the most feared teams in international <strong>Valorant</strong>. Known for jaw-dropping entry fragging and clutch potential, he has consistently performed at the highest level in <strong>VCT events</strong>. With an <strong>eDPI of 256</strong>, his settings are built around an aggressive, aim-confident style that prioritizes fast target acquisition and one-tap headshots.",
      },
      {
        type: "heading",
        level: 2,
        text: "Aspas Mouse Settings",
      },
      {
        type: "specs",
        label: "Mouse & Sensitivity",
        rows: [
          ["DPI", "800"],
          ["In-Game Sensitivity", "0.32"],
          ["eDPI", "256"],
          ["Polling Rate", "1000 Hz"],
          ["Raw Input Buffer", "On"],
          ["Windows Sensitivity", "6/11"],
          ["Mouse Acceleration", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Crosshair Settings",
      },
      {
        type: "specs",
        label: "Crosshair",
        rows: [
          ["Color", "White"],
          ["Inner Lines Opacity", "1"],
          ["Inner Lines Length", "4"],
          ["Inner Lines Thickness", "2"],
          ["Inner Lines Offset", "2"],
          ["Outer Lines", "Off"],
          ["Center Dot", "Off"],
          ["Movement / Firing Error", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Video & Graphics Settings",
      },
      {
        type: "specs",
        label: "Video Settings",
        rows: [
          ["Resolution", "1920x1080"],
          ["Display Mode", "Fullscreen"],
          ["Frame Rate Limit", "Unlocked"],
          ["Material Quality", "Low"],
          ["Texture Quality", "Low"],
          ["Detail Quality", "Low"],
          ["UI Quality", "Low"],
          ["Vignette", "Off"],
          ["Anti-Aliasing", "MSAA 4x"],
          ["Anisotropic Filtering", "4x"],
          ["Bloom", "Off"],
          ["Distortion", "Off"],
          ["First Person Shadows", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Gear & Setup",
      },
      {
        type: "specs",
        label: "Aspas's Peripherals",
        rows: [
          ["Mouse", "Logitech G Pro X Superlight 2"],
          ["Mousepad", "Logitech G640 (XL)"],
          ["Keyboard", "HyperX Alloy Origins 65"],
          ["Monitor", "LG UltraGear 27GR95U (240Hz)"],
          ["Headset", "Logitech G Pro X 2"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "How to Use Aspas's Settings",
      },
      {
        type: "list",
        style: "bullet",
        items: [
          "eDPI 256 is a <strong>medium sensitivity</strong> comfortable for both flick shots and tracking — a great starting point for duelists.",
          "Play <strong>Deathmatch for 20–30 minutes</strong> before every ranked session to activate your aim.",
          "Use a <strong>lightweight mouse under 65g</strong> for the fast swipe movements Aspas makes when entry fragging.",
          "Set all graphics to <strong>Low</strong> and remove Bloom/Distortion for maximum visual clarity on enemies.",
          "Focus on <strong>swing timing</strong> — Aspas wins duels by taking fights at the right moment, not just by having good aim.",
          "Practice <strong>one-tap Deathmatch</strong> (stop and shoot) rather than spray-and-pray to build Aspas-style precision.",
        ],
      },
      {
        type: "callout",
        variant: "tip",
        html: "Aspas's real secret is <strong>raw aim practice volume</strong>. He plays Deathmatch and uses aim trainers for hours every day. His settings are good, but the hours he puts into aim development are what make the difference at the professional level.",
      },
      {
        type: "internal-links",
        title: "Related Valorant Guides",
        links: [
          { text: "TenZ Valorant Settings & Crosshair", href: "/pro-settings/valorant/tenz-valorant-settings/" },
          { text: "Demon1 Valorant Settings & Sensitivity", href: "/pro-settings/valorant/demon1-valorant-settings/" },
          { text: "Best Valorant Agents for Entry Fragging", href: "/guides/valorant/best-valorant-agents-entry-frag/" },
        ],
      },
    ],
    faqs: [
      { question: "What sensitivity does Aspas use in Valorant?", answer: "Aspas uses 800 DPI with 0.32 in-game sensitivity for an eDPI of 256. This is a medium sensitivity that balances flick speed with precision." },
      { question: "What resolution does Aspas play on?", answer: "Aspas plays on 1920x1080 native resolution with all video settings on Low except for Anisotropic Filtering set to 4x." },
    ],
  },
  {
    title: "ZywOo CS2 Settings, Crosshair & Config (2026)",
    slug: "zywoo-cs2-settings",
    description:
      "ZywOo's CS2 settings breakdown: crosshair, sensitivity, viewmodel, launch options, and full PC specs for 2026.",
    category: "pro-settings",
    subcategory: "cs2",
    tags: ["cs2", "zywoo", "pro-settings", "vitality"],
    date: "2026-03-08",
    author: "RaidGG Team",
    player: "ZywOo",
    readTime: "6 min",
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&h=450&fit=crop",
    imageAlt: "Pro gaming mouse matching ZywOo CS2 setup",
    sections: [
      {
        type: "paragraph",
        html: "<strong>ZywOo</strong> (Mathieu Herbaut) is widely considered one of the greatest <strong>Counter-Strike</strong> players of all time, having won multiple <strong>Major Championships</strong> and individual awards with <strong>Team Vitality</strong>. His transition from CS:GO to CS2 was seamless, and he continues to dominate with his remarkably consistent aim and game-changing clutch plays. As one of the world's best <strong>AWPers</strong>, his settings prioritize precision and stability.",
      },
      {
        type: "heading",
        level: 2,
        text: "ZywOo Mouse Settings",
      },
      {
        type: "specs",
        label: "Mouse & Sensitivity",
        rows: [
          ["DPI", "400"],
          ["In-Game Sensitivity", "2.0"],
          ["eDPI", "800"],
          ["Polling Rate", "1000 Hz"],
          ["Raw Input", "On"],
          ["Windows Sensitivity", "6/11"],
          ["Mouse Acceleration", "Off"],
          ["Zoom Sensitivity Multiplier", "0.818"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Crosshair & Config Settings",
      },
      {
        type: "specs",
        label: "Crosshair",
        rows: [
          ["Style", "Static"],
          ["Color", "Green"],
          ["Size", "2"],
          ["Thickness", "0"],
          ["Gap", "-3"],
          ["Dot", "Off"],
          ["Outline", "Off"],
          ["cl_crosshair_drawoutline", "0"],
          ["cl_crosshairgap", "-3"],
          ["cl_crosshairsize", "2"],
          ["cl_crosshairthickness", "0"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Video & Graphics Settings",
      },
      {
        type: "specs",
        label: "Video Settings",
        rows: [
          ["Resolution", "1920x1080"],
          ["Aspect Ratio", "16:9"],
          ["Display Mode", "Fullscreen"],
          ["Refresh Rate", "360 Hz"],
          ["Global Shadow Quality", "Low"],
          ["Model / Texture Detail", "Low"],
          ["Effect Detail", "Low"],
          ["Shader Detail", "Low"],
          ["Multicore Rendering", "Enabled"],
          ["Multisampling Anti-Aliasing", "None"],
          ["FXAA Anti-Aliasing", "Disabled"],
          ["Texture Filtering Mode", "Bilinear"],
          ["Vertical Sync", "Disabled"],
          ["Motion Blur", "Disabled"],
          ["Boost Player Contrast", "Enabled"],
          ["FPS Max", "999"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Gear & Setup",
      },
      {
        type: "specs",
        label: "ZywOo's Peripherals",
        rows: [
          ["Mouse", "Logitech G Pro X Superlight 2"],
          ["Mousepad", "Logitech G640 (XL)"],
          ["Keyboard", "Logitech G Pro X Keyboard"],
          ["Monitor", "Zowie XL2566K (360Hz TN)"],
          ["Headset", "Logitech G Pro X 2 Wireless"],
          ["PC CPU", "Intel Core i9-14900K"],
          ["PC GPU", "NVIDIA RTX 4090"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "How to Use ZywOo's Settings",
      },
      {
        type: "list",
        style: "bullet",
        items: [
          "eDPI 800 is the <strong>sweet spot for CS2 AWPers</strong> — fast enough for rifle duels, precise enough for long-range shots.",
          "Use a <strong>static crosshair</strong> (not dynamic) — it removes distracting movement and trains you to stop fully before shooting.",
          "Enable <strong>Boost Player Contrast</strong> in video settings to make enemies stand out more clearly against backgrounds.",
          "Keep <strong>all shadow and effect settings on Low</strong> — visual clutter is the enemy of enemy detection.",
          "Set <strong>Zoom Sensitivity to 0.818</strong> (360/FOV formula) so your AWP muscle memory matches your rifle muscle memory.",
          "Commit to your sensitivity — ZywOo's biggest advantage is <strong>never changing his settings</strong>, allowing deep muscle memory.",
        ],
      },
      {
        type: "callout",
        variant: "tip",
        html: "<strong>Stop changing your settings.</strong> ZywOo's philosophy is simple: find reasonable settings, lock them in, and practice for months. Every sensitivity change resets your muscle memory. Pick a number and commit.",
      },
      {
        type: "internal-links",
        title: "Related CS2 Guides",
        links: [
          { text: "Best CS2 Crosshair Codes", href: "/guides/cs2/best-cs2-crosshair-codes/" },
          { text: "Best CS2 Settings for FPS", href: "/guides/cs2/best-cs2-settings-fps/" },
          { text: "CS2 Launch Options Guide", href: "/guides/cs2/cs2-launch-options/" },
        ],
      },
    ],
    faqs: [
      { question: "What sensitivity does ZywOo use in CS2?", answer: "ZywOo plays on 400 DPI with 2.0 in-game sensitivity for an eDPI of 800. This is a standard medium sensitivity common among CS2 pros." },
      { question: "What crosshair does ZywOo use?", answer: "ZywOo uses a small static green crosshair with gap -3, thickness 0, and size 2. No dot, no outline. It's clean and minimal for precise aiming." },
      { question: "What monitor does ZywOo use?", answer: "ZywOo uses the Zowie XL2566K, a 360Hz TN panel monitor. The ultra-high refresh rate provides the smoothest possible motion clarity for competitive play." },
    ],
  },
  {
    title: "iFerg COD Mobile Settings & HUD Layout (2026)",
    slug: "iferg-cod-mobile-settings",
    description:
      "iFerg's complete COD Mobile setup: HUD layout, sensitivity, graphics settings, and device info for 2026.",
    category: "pro-settings",
    subcategory: "cod-mobile",
    tags: ["cod-mobile", "iferg", "pro-settings"],
    date: "2026-03-07",
    author: "RaidGG Team",
    player: "iFerg",
    readTime: "5 min",
    image: "https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&h=450&fit=crop",
    imageAlt: "Mechanical keyboard for iFerg COD Mobile settings",
    sections: [
      {
        type: "paragraph",
        html: "<strong>iFerg</strong> is one of the most influential figures in <strong>COD Mobile</strong>, bridging the gap between competitive play and content creation. With millions of followers across YouTube and social media, he has shaped how an entire generation of mobile FPS players approach their settings. His <strong>4-finger claw grip on iPad</strong> setup showcases what is possible on mobile when you combine optimized settings with dedicated practice.",
      },
      {
        type: "heading",
        level: 2,
        text: "iFerg COD Mobile Sensitivity Settings",
      },
      {
        type: "specs",
        label: "Sensitivity",
        rows: [
          ["Sensitivity Mode", "Standard"],
          ["Standard (Hip-Fire)", "85"],
          ["ADS (Iron Sight)", "75"],
          ["ADS (2x Scope)", "70"],
          ["ADS (3x Scope)", "65"],
          ["ADS (4x Scope)", "55"],
          ["ADS (6x Scope)", "45"],
          ["ADS (Sniper Scope)", "40"],
          ["Gyroscope", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "HUD & Controls Layout",
      },
      {
        type: "specs",
        label: "Controls",
        rows: [
          ["Control Style", "4-Finger Claw (iPad)"],
          ["Left Fire Button", "Top-left corner"],
          ["Right Fire Button", "Top-right corner"],
          ["Aim (Left Thumb)", "Bottom-left joystick"],
          ["Move (Right Thumb)", "Bottom-right joystick area"],
          ["Jump / Crouch", "Right thumb accessible"],
          ["ADS Button", "Dedicated (no tap-to-ADS)"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Graphics Settings",
      },
      {
        type: "specs",
        label: "Video & Graphics",
        rows: [
          ["Graphics Quality", "Very High"],
          ["Frame Rate", "Max (60 FPS on iPad Pro)"],
          ["Depth of Field", "Off"],
          ["Bloom", "Off"],
          ["Style", "Default"],
          ["Auto Adjust Graphics", "Off"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "Gear & Device Setup",
      },
      {
        type: "specs",
        label: "iFerg's Devices",
        rows: [
          ["Primary Device", "iPad Pro M4 (12.9-inch)"],
          ["Secondary Device", "iPhone 16 Pro Max"],
          ["Display", "12.9-inch Liquid Retina XDR, 120Hz"],
          ["Processor", "Apple M4"],
          ["Accessories", "Gaming trigger attachment, phone stand"],
          ["Controls Layout", "4-Finger Claw"],
        ],
      },
      {
        type: "heading",
        level: 2,
        text: "How to Use iFerg's Settings",
      },
      {
        type: "list",
        style: "bullet",
        items: [
          "Transition to claw grip <strong>gradually</strong> — start by moving just the right fire button to the top corner and using one index finger.",
          "Only add a second top button once the first feels completely natural — <strong>give it at least a week</strong> per new finger.",
          "iPad players need <strong>higher sensitivity than phone players</strong> — the larger screen requires bigger swipes for the same movement.",
          "Customize <strong>per-scope sensitivity</strong> carefully; sniper scopes need significantly lower values than hip-fire.",
          "Turn off <strong>Depth of Field and Bloom</strong> for cleaner visuals and easier enemy spotting.",
          "Use <strong>Very High graphics</strong> on iPad Pro M4 — it can handle it without frame drops.",
        ],
      },
      {
        type: "callout",
        variant: "warning",
        html: "<strong>Claw grip takes weeks to feel natural.</strong> Do not jump straight to 4 fingers — build up one finger at a time over several weeks. Trying to switch everything at once leads to frustration and poor gameplay. Patience is key.",
      },
      {
        type: "internal-links",
        title: "Related COD Mobile Guides",
        links: [
          { text: "Best COD Mobile Sensitivity Settings", href: "/guides/cod-mobile/best-cod-mobile-sensitivity/" },
          { text: "COD Mobile Best Guns Tier List", href: "/guides/cod-mobile/best-guns-tier-list/" },
          { text: "COD Mobile Redeem Codes (Today)", href: "/redeem-codes/cod-mobile/cod-mobile-redeem-codes-today/" },
        ],
      },
    ],
    faqs: [
      { question: "What device does iFerg use for COD Mobile?", answer: "iFerg primarily plays on iPad Pro M4 with a gaming trigger attachment. He also uses iPhone 16 Pro Max for casual gameplay and content creation." },
      { question: "Does iFerg use claw grip?", answer: "Yes, iFerg plays with a 4-finger claw setup on iPad. His HUD layout is optimized for claw grip with fire buttons on top corners and movement controls at the bottom." },
      { question: "What are iFerg's sensitivity settings?", answer: "iFerg uses Standard sensitivity mode with 85 for Standard, 70 for ADS, and custom values per scope. He fine-tunes sensitivity for each weapon class." },
    ],
  },
];

export default posts;
